In [1]:
from datetime import datetime

In [2]:
from pathlib import Path

In [3]:
datetime.today().strftime("%m-%d-%Y")

'06-25-2026'

In [3]:
project_dir =Path()

In [19]:
items = ("1","2 ","2#","4-")

cleaned = [items.strip() for items in items]

In [5]:
import pandas as pd

In [28]:
df = pd.read_csv(project_dir/"san_diego_10_year_weather.csv")

In [29]:
df

,time,temperature_2m,relative_humidity_2m,cloud_cover,pressure_msl,wind_speed_10m,precipitation
0,2016-01-01T00:00,7.9,74,0,1018.1,11.3,0.0
1,2016-01-01T01:00,7.5,73,0,1017.7,11.9,0.0
2,2016-01-01T02:00,7.1,75,0,1017.5,12.2,0.0
3,2016-01-01T03:00,6.8,75,0,1017.7,13.7,0.0
4,2016-01-01T04:00,6.6,76,0,1017.5,12.6,0.0
...,...,...,...,...,...,...,...
87667,2025-12-31T19:00,15.2,97,100,1015.3,2.8,0.7
87668,2025-12-31T20:00,15.3,93,100,1015.0,8.3,0.0
87669,2025-12-31T21:00,15.6,90,100,1015.2,6.9,0.0
87670,2025-12-31T22:00,15.6,91,100,1015.9,2.1,0.0
87671,2025-12-31T23:00,15.4,91,100,1016.4,4.5,0.1

In [30]:
df['time'] = (pd.to_datetime(df['time'])).dt.floor("15min").dt.strftime("%d-%m-%Y-%H:%M")

In [31]:
df

,time,temperature_2m,relative_humidity_2m,cloud_cover,pressure_msl,wind_speed_10m,precipitation
0,01-01-2016-00:00,7.9,74,0,1018.1,11.3,0.0
1,01-01-2016-01:00,7.5,73,0,1017.7,11.9,0.0
2,01-01-2016-02:00,7.1,75,0,1017.5,12.2,0.0
3,01-01-2016-03:00,6.8,75,0,1017.7,13.7,0.0
4,01-01-2016-04:00,6.6,76,0,1017.5,12.6,0.0
...,...,...,...,...,...,...,...
87667,31-12-2025-19:00,15.2,97,100,1015.3,2.8,0.7
87668,31-12-2025-20:00,15.3,93,100,1015.0,8.3,0.0
87669,31-12-2025-21:00,15.6,90,100,1015.2,6.9,0.0
87670,31-12-2025-22:00,15.6,91,100,1015.9,2.1,0.0
87671,31-12-2025-23:00,15.4,91,100,1016.4,4.5,0.1

In [22]:
data = pd.Series(items)

In [36]:
df['temperature_2m'] = df['temperature_2m'].str.replace(" ","",regex=False).str.replace(r"[^\d.]","",regex=True)

AttributeError: Can only use .str accessor with string values!

In [4]:
import pandas as pd
import numpy as np

# A simulated chaotic dataset to practice string cleaning and formatting
raw_data = {
    'raw_timestamp': [
        "2025-12-31T19:00",      # ISO Standard
        "2025/12/31 19:15:00",   # Slashes and spaces
        "31-12-2025 19:30",      # European style
        "2025-12-31T19:45:30Z",  # UTC format
        None                     # Missing entry
    ],
    'temperature_dirty': [
        "23.5 °C",               # Standard string with units
        "  24.1 C ",             # Extra leading/trailing spaces
        "22.8#",                 # Corrupted symbol
        25.3,                    # Already a float! (This throws the error)
        "24.0"                   # Clean string decimal
    ],
    'energy_demand_kw': [
        "4,500 kw",              # Commas as thousands separators
        "4650   ",               # Massive trailing whitespace
        "4-700",                 # Typo hyphen instead of a number separator
        "4750kw",                # No spaces between number and text
        "UNKNOWN"                # Text anomaly
    ]
}

df = pd.DataFrame(raw_data)
print("--- RAW DILEMMAS DATAFRAME ---")
print(df)
print("\n--- COLUMN DATA TYPES ---")
print(df.dtypes)

--- RAW DILEMMAS DATAFRAME ---
          raw_timestamp temperature_dirty energy_demand_kw
0      2025-12-31T19:00           23.5 °C         4,500 kw
1   2025/12/31 19:15:00           24.1 C           4650
2      31-12-2025 19:30             22.8#            4-700
3  2025-12-31T19:45:30Z              25.3           4750kw
4                  None              24.0          UNKNOWN

--- COLUMN DATA TYPES ---
raw_timestamp        object
temperature_dirty    object
energy_demand_kw     object
dtype: object

In [30]:
df

      raw_timestamp  temperature_dirty  energy_demand_kw
0  31-12-2025-19:00               23.5            4500.0
1  31-12-2025-19:15               24.1            4650.0
2  31-12-2025-19:30               22.8            4700.0
3  31-12-2025-19:45               23.4            4750.0
4               NaN               24.0               NaN

In [7]:
import numpy as np

In [21]:
df['temperature_dirty'] = (df['temperature_dirty'].str.replace(" ","",regex=False).str.replace(r"[^\d.]","",regex=True)).astype(float)

In [8]:
df['energy_demand_kw']=df['energy_demand_kw'].replace("UNKNOWN",np.nan)

In [24]:
df['energy_demand_kw'] = (df['energy_demand_kw'].str.replace(" ","",regex=False).str.replace(r"[^\d]","",regex=True)).astype(float)

In [12]:
df['raw_timestamp'] = pd.to_datetime(df['raw_timestamp'],format='mixed',utc=True)

In [ ]:
df['temperature_dirty']

In [28]:
df[['temperature_dirty','energy_demand_kw']].interpolate(inplace=True)

C:\Users\Shaaf\AppData\Local\Temp\ipykernel_19592\1094639538.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['temperature_dirty','energy_demand_kw']].interpolate(inplace=True)

In [14]:
df['raw_timestamp']=df['raw_timestamp'].dt.strftime("%d-%m-%Y-%H:%M")

In [90]:
df.drop(4,inplace=True,axis=0)

In [91]:
df['temperature_dirty'] = df['temperature_dirty'].str.replace(" ","",regex=False).str.replace(r"[^\d.]","",regex=True)

In [92]:
df['energy_demand_kw'] = df['energy_demand_kw'].str.replace(" ","",regex=False).str.replace(r"[^\d]","",regex=True)

In [ ]:
# df['raw_timestamp'] = df['raw_timestamp'].str.replace(" ","",regex=False).str.replace(r"[^\d:-]","",regex=True)

In [93]:
df

          raw_timestamp temperature_dirty energy_demand_kw
0      2025-12-31T19:00              23.5             4500
1   2025/12/31 19:15:00              24.1             4650
2      31-12-2025 19:30              22.8             4700
3  2025-12-31T19:45:30Z               NaN             4750

In [94]:
df['raw_timestamp'] = pd.to_datetime(df['raw_timestamp'],format='mixed')

C:\Users\Shaaf\AppData\Local\Temp\ipykernel_21928\41139357.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['raw_timestamp'] = pd.to_datetime(df['raw_timestamp'],format='mixed')

In [108]:
df

      raw_timestamp  temperature_dirty energy_demand_kw
0  31-12-2025-19:00               23.5             4500
1  31-12-2025-19:15               24.1             4650
2  31-12-2025-19:30               22.8             4700
3  31-12-2025-19:45               22.8             4750

In [96]:
df.dtypes

raw_timestamp        object
temperature_dirty    object
energy_demand_kw     object
dtype: object

In [101]:
df['raw_timestamp'] = (pd.to_datetime(df['raw_timestamp'],format='mixed',utc=True)).dt.strftime("%d-%m-%Y-%H:%M")

In [106]:
df['temperature_dirty'] = df['temperature_dirty'].astype(float)

In [107]:
df['temperature_dirty'].interpolate(inplace=True)

C:\Users\Shaaf\AppData\Local\Temp\ipykernel_21928\2742824682.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['temperature_dirty'].interpolate(inplace=True)

In [1]:
a = {"x": 1}

b = a

b["y"] = 2

print(a)

{'x': 1, 'y': 2}

In [2]:
x = (1, 2, 3)

try:
    x[0] = 10
except Exception as e:
    print(type(e).__name__)

TypeError

In [3]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["John", "Sara", "Mike"],
    "Salary": [50000, 60000, 70000]
})

In [4]:
df2 = df

df2["Salary"] = df2["Salary"] * 2

print(df)

   Name  Salary
0  John  100000
1  Sara  120000
2  Mike  140000

In [5]:
df

   Name  Salary
0  John  100000
1  Sara  120000
2  Mike  140000

In [6]:
print(id(df))

1969233428896

In [1]:
import joblib
from pathlib import Path
from pydantic import BaseModel

project_dir=Path()
model_dir= project_dir/'models'

In [2]:
xgb_demand_model = joblib.load(model_dir/"xgb_demand_forecast_model.pkl")

In [3]:
xgb_demand_model

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.01, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=800,
             n_jobs=None, num_parallel_tree=None, ...)