In [79]:
import pandas as pd 
import numpy as np
import duckdb

In [80]:
con = duckdb.connect(database=':memory:')

In [82]:
df_raw = con.execute(r"""
    SELECT * FROM read_json_auto("C:\Users\Shaaf\Desktop\Data Science\Practice Projects\DeepLearning\Energy Predictions\Data\EBA\EBA.txt")
""").df()

In [86]:
df_raw = con.execute(r"""
    SELECT *
    FROM read_json_auto('C:/Users/Shaaf/Desktop/Data Science/Practice Projects/DeepLearning/Energy Predictions/Data/EBA/EBA.txt')
    WHERE name ILIKE '%solar%'
""").df()

In [87]:
df_raw

,series_id,name,units,f,description,start,end,last_updated,data
0,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,"[[20260114T07, 0], [20260114T06, 0], [20260114..."
1,EBA.BANC-ALL.NG.SUN.HL,Net generation from solar for Balancing Author...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20181231T16-08,20260113T23-08,15-JAN-26 05.04.04 AM,"[[20260113T23-08, 0], [20260113T22-08, 0], [20..."
2,EBA.BPAT-ALL.NG.SUN.H,Net generation from solar for Bonneville Power...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,"[[20260114T07, 0], [20260114T06, -1], [2026011..."
3,EBA.BPAT-ALL.NG.SUN.HL,Net generation from solar for Bonneville Power...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20181231T16-08,20260113T23-08,15-JAN-26 05.04.04 AM,"[[20260113T23-08, 0], [20260113T22-08, -1], [2..."
4,EBA.CENT-ALL.NG.SUN.H,Net generation from solar for Central (region)...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T05,15-JAN-26 05.04.04 AM,"[[20260114T05, 813], [20260114T04, 813], [2026..."
...,...,...,...,...,...,...,...,...,...
111,EBA.PSCO-ALL.NG.SUN.HL,Net generation from solar for Public Service C...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20181231T17-07,20260113T23-07,15-JAN-26 05.04.04 AM,"[[20260113T23-07, -6], [20260113T22-07, -5], [..."
112,EBA.PSEI-ALL.NG.SUN.H,Net generation from solar for Puget Sound Ener...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20211128T09,20260114T07,15-JAN-26 05.04.04 AM,"[[20260114T07, 0], [20260114T06, 0], [20260114..."
113,EBA.PSEI-ALL.NG.SUN.HL,Net generation from solar for Puget Sound Ener...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20211128T01-08,20260113T23-08,15-JAN-26 05.04.04 AM,"[[20260113T23-08, 0], [20260113T22-08, 0], [20..."
114,EBA.SIKE-ALL.NG.SUN.ADJ.H,SIKE (Adjusted) Hourly Net Generation from Sol...,MWh,H,SIKE (Adjusted) Hourly Net Generation from Sol...,20190101T00,20260113T06,15-JAN-26 05.04.04 AM,"[[20260113T06, 241], [20260113T05, 208], [2026..."
115,EBA.SIKE-ALL.NG.SUN.ADJ.HL,SIKE (Adjusted) Hourly Net Generation from Sol...,MWh,HL,SIKE (Adjusted) Hourly Net Generation from Sol...,20181231T18-06,20260113T00-06,15-JAN-26 05.04.04 AM,"[[20260113T00-06, 241], [20260112T23-06, 208],..."

In [84]:
df_raw[["New Name","Everyhting else"]]= df_raw["name"].str.split(",",n=1,expand=True)

In [85]:
df_raw.to_csv("01-EBA_raw.csv", index=False)

In [45]:
import pandas as pd
import re

# keywords to ignore
ignore_keywords = [
    "co2", "import", "export",
    "coal", "petroleum", "refinery",
    "diesel", "petrol", "gasoline",
    "biofuel", "biomass", "lignite",
    "oil", "kerosene",
    "natural gas", "emission","geothermal","fossil","nuclear","propane"
]

pattern = "|".join(ignore_keywords)

# keep rows that DO NOT contain these keywords
df_clean = df[~df["name"].str.lower().str.contains(pattern, regex=True)]

print(f"Original rows: {len(df)}")
print(f"After filtering: {len(df_clean)}")

Original rows: 3068
After filtering: 1956

In [46]:
df_clean

,series_id,name,units,f,description,start,end,last_updated,data
0,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,"[array(['20260114T07', '0'], dtype=object)\n a..."
1,EBA.BANC-ALL.NG.SUN.HL,Net generation from solar for Balancing Author...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20181231T16-08,20260113T23-08,15-JAN-26 05.04.04 AM,"[array(['20260113T23-08', '0'], dtype=object)\..."
2,EBA.BANC-ALL.NG.WAT.H,Net generation from hydro for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,"[array(['20260114T07', '1297'], dtype=object)\..."
3,EBA.BANC-ALL.NG.WAT.HL,Net generation from hydro for Balancing Author...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20181231T16-08,20260113T23-08,15-JAN-26 05.04.04 AM,"[array(['20260113T23-08', '1297'], dtype=objec..."
8,EBA.BPAT-ALL.NG.OTH.H,Net generation from other for Bonneville Power...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,"[array(['20260114T07', '138'], dtype=object)\n..."
...,...,...,...,...,...,...,...,...,...
3055,EBA.LGEE-MISO.ID.HL,Actual Net Interchange for Louisville Gas and ...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20190101T01-05,20260113T00-05,15-JAN-26 05.04.04 AM,"[array(['20260113T00-05', '-462'], dtype=objec..."
3056,EBA.SOCO-MISO.ID.H,Actual Net Interchange for Southern Company Se...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260113T06,15-JAN-26 05.04.04 AM,"[array(['20260113T06', '452'], dtype=object)\n..."
3057,EBA.SOCO-MISO.ID.HL,Actual Net Interchange for Southern Company Se...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20181231T18-06,20260113T00-06,15-JAN-26 05.04.04 AM,"[array(['20260113T00-06', '452'], dtype=object..."
3058,EBA.EPE-SWPP.ID.H,Actual Net Interchange for El Paso Electric Co...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260113T07,15-JAN-26 05.04.04 AM,"[array(['20260113T07', '0'], dtype=object)\n a..."
3059,EBA.EPE-SWPP.ID.HL,Actual Net Interchange for El Paso Electric Co...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20181231T17-07,20260113T00-07,15-JAN-26 05.04.04 AM,"[array(['20260113T00-07', '0'], dtype=object)\..."

In [47]:
df_clean[["New Name","Everyhting else"]]= df_clean["name"].str.split(",",n=1,expand=True)

C:\Users\Shaaf\AppData\Local\Temp\ipykernel_16528\1319656362.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[["New Name","Everyhting else"]]= df_clean["name"].str.split(",",n=1,expand=True)
C:\Users\Shaaf\AppData\Local\Temp\ipykernel_16528\1319656362.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean[["New Name","Everyhting else"]]= df_clean["name"].str.split(",",n=1,expand=True)

In [48]:
df_clean['New Name'].nunique()

836

In [52]:
# Use the | (OR) operator inside a single string
df_solar = df_clean[df_clean['New Name'].str.contains('solar|photovoltaic', case=False, na=False)]

In [53]:
df_solar['New Name'].nunique()

58

In [54]:
df_solar

,series_id,name,units,f,description,start,end,last_updated,data,New Name,Everyhting else
0,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,"[array(['20260114T07', '0'], dtype=object)\n a...",Net generation from solar for Balancing Author...,hourly - UTC time
1,EBA.BANC-ALL.NG.SUN.HL,Net generation from solar for Balancing Author...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20181231T16-08,20260113T23-08,15-JAN-26 05.04.04 AM,"[array(['20260113T23-08', '0'], dtype=object)\...",Net generation from solar for Balancing Author...,hourly - local time
10,EBA.BPAT-ALL.NG.SUN.H,Net generation from solar for Bonneville Power...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,"[array(['20260114T07', '0'], dtype=object)\n a...",Net generation from solar for Bonneville Power...,hourly - UTC time
11,EBA.BPAT-ALL.NG.SUN.HL,Net generation from solar for Bonneville Power...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20181231T16-08,20260113T23-08,15-JAN-26 05.04.04 AM,"[array(['20260113T23-08', '0'], dtype=object)\...",Net generation from solar for Bonneville Power...,hourly - local time
26,EBA.CENT-ALL.NG.SUN.H,Net generation from solar for Central (region)...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T05,15-JAN-26 05.04.04 AM,"[array(['20260114T05', '813'], dtype=object)\n...",Net generation from solar for Central (region),hourly - UTC time
...,...,...,...,...,...,...,...,...,...,...,...
1007,EBA.PSCO-ALL.NG.SUN.HL,Net generation from solar for Public Service C...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20181231T17-07,20260113T23-07,15-JAN-26 05.04.04 AM,"[array(['20260113T23-07', '-6'], dtype=object)...",Net generation from solar for Public Service C...,hourly - local time
1020,EBA.PSEI-ALL.NG.SUN.H,Net generation from solar for Puget Sound Ener...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20211128T09,20260114T07,15-JAN-26 05.04.04 AM,"[array(['20260114T07', '0'], dtype=object)\n a...",Net generation from solar for Puget Sound Energy,"Inc. (PSEI), hourly - UTC time"
1021,EBA.PSEI-ALL.NG.SUN.HL,Net generation from solar for Puget Sound Ener...,megawatthours,HL,Timestamps follow the ISO8601 standard (https:...,20211128T01-08,20260113T23-08,15-JAN-26 05.04.04 AM,"[array(['20260113T23-08', '0'], dtype=object)\...",Net generation from solar for Puget Sound Energy,"Inc. (PSEI), hourly - local time"
1286,EBA.SIKE-ALL.NG.SUN.ADJ.H,SIKE (Adjusted) Hourly Net Generation from Sol...,MWh,H,SIKE (Adjusted) Hourly Net Generation from Sol...,20190101T00,20260113T06,15-JAN-26 05.04.04 AM,"[array(['20260113T06', '241'], dtype=object)\n...",SIKE (Adjusted) Hourly Net Generation from Sol...,None
1287,EBA.SIKE-ALL.NG.SUN.ADJ.HL,SIKE (Adjusted) Hourly Net Generation from Sol...,MWh,HL,SIKE (Adjusted) Hourly Net Generation from Sol...,20181231T18-06,20260113T00-06,15-JAN-26 05.04.04 AM,"[array(['20260113T00-06', '241'], dtype=object...",SIKE (Adjusted) Hourly Net Generation from Sol...,None

In [64]:
import pandas as pd
import ast

# Assuming you've already loaded the data into df
# df = pd.read_csv('your_file.csv', sep='\t')

# Function to parse the array string
df = df_solar.copy()
import pandas as pd
import numpy as np
import re

# Function to parse the array string
def parse_array_column(array_str):
    # Remove outer quotes
    array_str = array_str.strip('"')
    
    # Extract all the timestamp-value pairs using regex
    pattern = r"array\(\['([^']+)',\s*'([^']+)'\]"
    matches = re.findall(pattern, array_str)
    
    return matches

# Parse the data column
df['parsed_data'] = df['data'].apply(parse_array_column)

# Explode to create one row per timestamp-value pair
df_exploded = df.explode('parsed_data')

# Extract timestamp and value from each tuple
df_exploded['timestamp'] = df_exploded['parsed_data'].apply(lambda x: x[0] if isinstance(x, tuple) else None)
df_exploded['value'] = df_exploded['parsed_data'].apply(lambda x: x[1] if isinstance(x, tuple) else None)

# Convert to appropriate types
df_exploded['value'] = pd.to_numeric(df_exploded['value'])
df_exploded['timestamp'] = pd.to_datetime(df_exploded['timestamp'], format='mixed')

# Drop the temporary columns
df_exploded = df_exploded.drop(['data', 'parsed_data'], axis=1)

# Reset index
df_exploded = df_exploded.reset_index(drop=True)

print(df_exploded.head(20))
print(f"\nTotal rows: {len(df_exploded)}")

                 series_id                                               name  \
0    EBA.BANC-ALL.NG.SUN.H  Net generation from solar for Balancing Author...
1    EBA.BANC-ALL.NG.SUN.H  Net generation from solar for Balancing Author...
2    EBA.BANC-ALL.NG.SUN.H  Net generation from solar for Balancing Author...
3    EBA.BANC-ALL.NG.SUN.H  Net generation from solar for Balancing Author...
4    EBA.BANC-ALL.NG.SUN.H  Net generation from solar for Balancing Author...
5    EBA.BANC-ALL.NG.SUN.H  Net generation from solar for Balancing Author...
6   EBA.BANC-ALL.NG.SUN.HL  Net generation from solar for Balancing Author...
7   EBA.BANC-ALL.NG.SUN.HL  Net generation from solar for Balancing Author...
8   EBA.BANC-ALL.NG.SUN.HL  Net generation from solar for Balancing Author...
9   EBA.BANC-ALL.NG.SUN.HL  Net generation from solar for Balancing Author...
10  EBA.BANC-ALL.NG.SUN.HL  Net generation from solar for Balancing Author...
11  EBA.BANC-ALL.NG.SUN.HL  Net generation from solar for Balancing Author...
12   EBA.BPAT-ALL.NG.SUN.H  Net generation from solar for Bonneville Power...
13   EBA.BPAT-ALL.NG.SUN.H  Net generation from solar for Bonneville Power...
14   EBA.BPAT-ALL.NG.SUN.H  Net generation from solar for Bonneville Power...
15   EBA.BPAT-ALL.NG.SUN.H  Net generation from solar for Bonneville Power...
16   EBA.BPAT-ALL.NG.SUN.H  Net generation from solar for Bonneville Power...
17   EBA.BPAT-ALL.NG.SUN.H  Net generation from solar for Bonneville Power...
18  EBA.BPAT-ALL.NG.SUN.HL  Net generation from solar for Bonneville Power...
19  EBA.BPAT-ALL.NG.SUN.HL  Net generation from solar for Bonneville Power...

            units   f                                        description  \
0   megawatthours   H  Timestamps follow the ISO8601 standard (https:...
1   megawatthours   H  Timestamps follow the ISO8601 standard (https:...
2   megawatthours   H  Timestamps follow the ISO8601 standard (https:...
3   megawatthours   H  Timestamps follow the ISO8601 standard (https:...
4   megawatthours   H  Timestamps follow the ISO8601 standard (https:...
5   megawatthours   H  Timestamps follow the ISO8601 standard (https:...
6   megawatthours  HL  Timestamps follow the ISO8601 standard (https:...
7   megawatthours  HL  Timestamps follow the ISO8601 standard (https:...
8   megawatthours  HL  Timestamps follow the ISO8601 standard (https:...
9   megawatthours  HL  Timestamps follow the ISO8601 standard (https:...
10  megawatthours  HL  Timestamps follow the ISO8601 standard (https:...
11  megawatthours  HL  Timestamps follow the ISO8601 standard (https:...
12  megawatthours   H  Timestamps follow the ISO8601 standard (https:...
13  megawatthours   H  Timestamps follow the ISO8601 standard (https:...
14  megawatthours   H  Timestamps follow the ISO8601 standard (https:...
15  megawatthours   H  Timestamps follow the ISO8601 standard (https:...
16  megawatthours   H  Timestamps follow the ISO8601 standard (https:...
17  megawatthours   H  Timestamps follow the ISO8601 standard (https:...
18  megawatthours  HL  Timestamps follow the ISO8601 standard (https:...
19  megawatthours  HL  Timestamps follow the ISO8601 standard (https:...

             start             end           last_updated  \
0      20190101T00     20260114T07  15-JAN-26 05.04.04 AM
1      20190101T00     20260114T07  15-JAN-26 05.04.04 AM
2      20190101T00     20260114T07  15-JAN-26 05.04.04 AM
3      20190101T00     20260114T07  15-JAN-26 05.04.04 AM
4      20190101T00     20260114T07  15-JAN-26 05.04.04 AM
5      20190101T00     20260114T07  15-JAN-26 05.04.04 AM
6   20181231T16-08  20260113T23-08  15-JAN-26 05.04.04 AM
7   20181231T16-08  20260113T23-08  15-JAN-26 05.04.04 AM
8   20181231T16-08  20260113T23-08  15-JAN-26 05.04.04 AM
9   20181231T16-08  20260113T23-08  15-JAN-26 05.04.04 AM
10  20181231T16-08  20260113T23-08  15-JAN-26 05.04.04 AM
11  20181231T16-08  20260113T23-08  15-JAN-26 05.04.04 AM
12     20190101T00     20260114T07  15-JAN-26 05.04.04 AM
13     20190101T00     20260114T07  15-JAN-26 05.04.04 AM
14     20190101T00     20260114T07  15-JAN-26 05.04.04 AM
15     20190101T00     20260114T07  15-JAN-26 05.04.04 AM
16     20190101T00     20260114T07  15-JAN-26 05.04.04 AM
17     20190101T00     20260114T07  15-JAN-26 05.04.04 AM
18  20181231T16-08  20260113T23-08  15-JAN-26 05.04.04 AM
19  20181231T16-08  20260113T23-08  15-JAN-26 05.04.04 AM

                                             New Name       Everyhting else  \
0   Net generation from solar for Balancing Author...     hourly - UTC time
1   Net generation from solar for Balancing Author...     hourly - UTC time
2   Net generation from solar for Balancing Author...     hourly - UTC time
3   Net generation from solar for Balancing Author...     hourly - UTC time
4   Net generation from solar for Balancing Author...     hourly - UTC time
5   Net generation from solar for Balancing Author...     hourly - UTC time
6   Net generation from solar for Balancing Author...   hourly - local time
7   Net generation from solar for Balancing Author...   hourly - local time
8   Net generation from solar for Balancing Author...   hourly - local time
9   Net generation from solar for Balancing Author...   hourly - local time
10  Net generation from solar for Balancing Author...   hourly - local time
11  Net generation from solar for Balancing Author...   hourly - local time
12  Net generation from solar for Bonneville Power...     hourly - UTC time
13  Net generation from solar for Bonneville Power...     hourly - UTC time
14  Net generation from solar for Bonneville Power...     hourly - UTC time
15  Net generation from solar for Bonneville Power...     hourly - UTC time
16  Net generation from solar for Bonneville Power...     hourly - UTC time
17  Net generation from solar for Bonneville Power...     hourly - UTC time
18  Net generation from solar for Bonneville Power...   hourly - local time
19  Net generation from solar for Bonneville Power...   hourly - local time

                    timestamp  value
0         2026-01-14 07:00:00      0
1         2026-01-14 06:00:00      0
2         2026-01-14 05:00:00      0
3         2019-01-01 02:00:00      1
4         2019-01-01 01:00:00      9
5         2019-01-01 00:00:00     63
6   2026-01-13 23:00:00-08:00      0
7   2026-01-13 22:00:00-08:00      0
8   2026-01-13 21:00:00-08:00      0
9   2018-12-31 18:00:00-08:00      1
10  2018-12-31 17:00:00-08:00      9
11  2018-12-31 16:00:00-08:00     63
12        2026-01-14 07:00:00      0
13        2026-01-14 06:00:00     -1
14        2026-01-14 05:00:00     -1
15        2019-01-01 02:00:00      0
16        2019-01-01 01:00:00      0
17        2019-01-01 00:00:00      2
18  2026-01-13 23:00:00-08:00      0
19  2026-01-13 22:00:00-08:00     -1

Total rows: 684

C:\Users\Shaaf\AppData\Local\Temp\ipykernel_16528\3684834908.py:36: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df_exploded['timestamp'] = pd.to_datetime(df_exploded['timestamp'], format='mixed')

In [65]:
# df_exploded = df_exploded[df_exploded["units"] != "CO2 metric tons"]
df_exploded['units'].value_counts()

units
megawatthours    672
MWh               12
Name: count, dtype: int64

In [66]:
df_exploded.to_csv("Final EBA Cleaned.csv",index=False)

In [69]:
a=df_exploded[df_exploded['series_id']=='EBA.BANC-ALL.NG.SUN.H']

In [71]:
df_exploded

,series_id,name,units,f,description,start,end,last_updated,New Name,Everyhting else,timestamp,value
0,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2026-01-14 07:00:00,0
1,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2026-01-14 06:00:00,0
2,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2026-01-14 05:00:00,0
3,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2019-01-01 02:00:00,1
4,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2019-01-01 01:00:00,9
...,...,...,...,...,...,...,...,...,...,...,...,...
679,EBA.SIKE-ALL.NG.SUN.ADJ.HL,SIKE (Adjusted) Hourly Net Generation from Sol...,MWh,HL,SIKE (Adjusted) Hourly Net Generation from Sol...,20181231T18-06,20260113T00-06,15-JAN-26 05.04.04 AM,SIKE (Adjusted) Hourly Net Generation from Sol...,None,2026-01-12 23:00:00-06:00,208
680,EBA.SIKE-ALL.NG.SUN.ADJ.HL,SIKE (Adjusted) Hourly Net Generation from Sol...,MWh,HL,SIKE (Adjusted) Hourly Net Generation from Sol...,20181231T18-06,20260113T00-06,15-JAN-26 05.04.04 AM,SIKE (Adjusted) Hourly Net Generation from Sol...,None,2026-01-12 22:00:00-06:00,205
681,EBA.SIKE-ALL.NG.SUN.ADJ.HL,SIKE (Adjusted) Hourly Net Generation from Sol...,MWh,HL,SIKE (Adjusted) Hourly Net Generation from Sol...,20181231T18-06,20260113T00-06,15-JAN-26 05.04.04 AM,SIKE (Adjusted) Hourly Net Generation from Sol...,None,2018-12-31 20:00:00-06:00,-2
682,EBA.SIKE-ALL.NG.SUN.ADJ.HL,SIKE (Adjusted) Hourly Net Generation from Sol...,MWh,HL,SIKE (Adjusted) Hourly Net Generation from Sol...,20181231T18-06,20260113T00-06,15-JAN-26 05.04.04 AM,SIKE (Adjusted) Hourly Net Generation from Sol...,None,2018-12-31 19:00:00-06:00,-37
683,EBA.SIKE-ALL.NG.SUN.ADJ.HL,SIKE (Adjusted) Hourly Net Generation from Sol...,MWh,HL,SIKE (Adjusted) Hourly Net Generation from Sol...,20181231T18-06,20260113T00-06,15-JAN-26 05.04.04 AM,SIKE (Adjusted) Hourly Net Generation from Sol...,None,2018-12-31 18:00:00-06:00,-75

In [70]:
a

,series_id,name,units,f,description,start,end,last_updated,New Name,Everyhting else,timestamp,value
0,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2026-01-14 07:00:00,0
1,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2026-01-14 06:00:00,0
2,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2026-01-14 05:00:00,0
3,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2019-01-01 02:00:00,1
4,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2019-01-01 01:00:00,9
5,EBA.BANC-ALL.NG.SUN.H,Net generation from solar for Balancing Author...,megawatthours,H,Timestamps follow the ISO8601 standard (https:...,20190101T00,20260114T07,15-JAN-26 05.04.04 AM,Net generation from solar for Balancing Author...,hourly - UTC time,2019-01-01 00:00:00,63

In [75]:
df_exploded['timestamp'].head(10)

0          2026-01-14 07:00:00
1          2026-01-14 06:00:00
2          2026-01-14 05:00:00
3          2019-01-01 02:00:00
4          2019-01-01 01:00:00
5          2019-01-01 00:00:00
6    2026-01-13 23:00:00-08:00
7    2026-01-13 22:00:00-08:00
8    2026-01-13 21:00:00-08:00
9    2018-12-31 18:00:00-08:00
Name: timestamp, dtype: object

In [76]:
df_exploded['timestamp'] = pd.to_datetime(
    df_exploded['timestamp'],
    utc=True
)

In [77]:
df_daily = df_exploded.groupby(df_exploded["timestamp"].dt.date)["value"].sum()

In [78]:
df_daily

timestamp
2019-01-01    13644
2019-12-25        0
2019-12-26        0
2019-12-27        0
2020-10-15        0
2021-11-28        0
2026-01-13     1308
2026-01-14    20450
Name: value, dtype: int64